name: 'Setup CCache'
inputs:
  ccache-path:  # id of input
    required: true
    default: '/usr/lib/ccache'
runs:
  using: "composite"
  steps:
      - name: Setup CCache
        shell: bash
        run: |
          eval $(printf 'PATH=${{ inputs.ccache-path }}:%s\n' "$PATH" | tee -a "$GITHUB_ENV")
          cat <<EOF >>"$GITHUB_ENV"
          CCACHE_MAXSIZE=500M
          CCACHE_DIR=$HOME/.cache/ccache
          CCACHE_BASEDIR=$PWD
          EOF
      - name: Cache compilation
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.compiler }}-${{ matrix.platform.os }}
          restore-keys: |
            ccache-${{ matrix.compiler }}